language: node_js
git:
  depth: 10
node_js:
  - "0.12"
install:
  - npm install -g grunt-cli
script: grunt test-js
after_success: grunt dist
deploy:
  provider: s3
  access_key_id:
    secure: FpgDfgXa4gtzj5BGcXeB1rmPp3LSOl9yVhHepbBV2jEZaIFM2wOOvaTikq0/jFEJjM7dJghu3LS3wKVHiaimmabGP7brOHrpbPqFg4nQohPFrSPInx5O7TJZ5lmMvyuRRNB+iQRnpVCjzK9KaLc7SY6JaP4SOUgigFB6R6a6DhA=
  secret_access_key:
    secure: iHf0K5aeqhlkRI+AacPClXcE1rTB+qI4St0zWXUvjxWrxeaLRtrNpbF7tEeoVgk4ZpwS6VIeJblpBSjayEoUvDdJmQMQhQosTHx52hn2avU8dKCU6yTJ+U3ClQg8Dh10SzC0Jiv4E9I4wfCDcT+/xewvs2kj/d5JuOLgufAVHZs=
  bucket: "cloudfront-eu-w"
  region: "eu-west-1"
  local_dir: init
  upload-dir: 8legd/bootstrap3-theme-water
