language: node_js
git:
  depth: 10
node_js:
  - "0.12"
before_install:
  - travis_retry sudo pip install -r test-infra/requirements.txt
  - rvm use 1.9.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)
  - if [ "$TWBS_TEST" = validate-html ]; then echo "ruby=$(basename $GEMDIR) jekyll=$JEKYLL_VERSION rouge=$ROUGE_VERSION" > pseudo_Gemfile.lock; fi
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip validator\]'; export TWBS_DO_VALIDATOR=$?; true
  - echo "$TRAVIS_COMMIT_MSG" | grep '\[skip sauce\]'; export TWBS_DO_SAUCE=$?; true
  - if [ "$TRAVIS_REPO_SLUG" = twbs-savage/bootstrap ]; then export TWBS_DO_VALIDATOR=0; fi
install:
  - npm install -g grunt-cli
  - ./test-infra/s3_cache.py download npm-modules
  - if [ "$TWBS_TEST" = validate-html ] && [ $TWBS_DO_VALIDATOR -ne 0 ]; then ./test-infra/s3_cache.py download rubygems; fi
script: grunt test
after_script:
  - if [ "$TRAVIS_REPO_SLUG" != twbs-savage/bootstrap ] && [ "$TWBS_TEST" = core ]; then ./test-infra/s3_cache.py upload npm-modules; fi
  - if [ "$TRAVIS_REPO_SLUG" != twbs-savage/bootstrap ] && [ "$TWBS_TEST" = validate-html ] && [ $TWBS_DO_VALIDATOR -ne 0 ]; then ./test-infra/s3_cache.py upload rubygems; fi
after_success: grunt dist
deploy:
  provider: s3
  access_key_id:
    secure: FpgDfgXa4gtzj5BGcXeB1rmPp3LSOl9yVhHepbBV2jEZaIFM2wOOvaTikq0/jFEJjM7dJghu3LS3wKVHiaimmabGP7brOHrpbPqFg4nQohPFrSPInx5O7TJZ5lmMvyuRRNB+iQRnpVCjzK9KaLc7SY6JaP4SOUgigFB6R6a6DhA=
  secret_access_key:
    secure: iHf0K5aeqhlkRI+AacPClXcE1rTB+qI4St0zWXUvjxWrxeaLRtrNpbF7tEeoVgk4ZpwS6VIeJblpBSjayEoUvDdJmQMQhQosTHx52hn2avU8dKCU6yTJ+U3ClQg8Dh10SzC0Jiv4E9I4wfCDcT+/xewvs2kj/d5JuOLgufAVHZs=
  bucket: "cloudfront-eu-w"
  region: "eu-west-1"
  local_dir: init
  upload-dir: 8legd/bootstrap3-theme-water
