language: node_js
git:
  depth: 10
node_js:
  - "0.12"
install:
  - npm install -g grunt-cli
  - npm install
script: grunt test-js
after_success: grunt dist
deploy:
  provider: s3
  access_key_id:
    secure: leB8EozPiLBG1XJZ63jZ9V4DT8YvcX8ve6x2HrJKdmKuMQE2uu6NlDzSpzaELTExVTWJLBRZymVs2xUsYD4KpX6mDOSah6NuJf6oeSG4r1OqzDVvDx+1sZp4FeuY9tJIHNnE5Y4VbnZXuQNLFt4VDwfuxX5DYJGTzpZzm6B+Le0=
  secret_access_key:
    secure: VQ93Dju5pmCGJbJaY4yhcQSplkd49n/cUocYrtqZJAhJS8TYNMNqthvD1l3X8YZd1np2ndSX2B49vEIAUTWcU5Nwo6BOVDoMDLxYVgKHlbBODp84c4x8aCj0QKU/tQSuyfNw8I8dDlGllgWHMbBa4Ubbinf51v0CkKha2lBr5v8=
  bucket: "cloudfront-eu-w"
  region: "eu-west-1"
  local_dir: dist
  upload-dir: 8legd/bootstrap3-theme-water
